spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 62855
      # 连接池配置
      initial-size: 50
      min-idle: 50
      max-active: 100
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.springboot.servie.*

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置 
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true
  #开启热部署
  devtools:
    restart:
      enabled: true

  # rabbitMQ
  rabbitmq:
    host: 127.0.0.1    # rabbitmq的主机地址
    port: 5672
    username: guest #rabbitmq的用户名，默认为guest
    password: guest #rabbitmq的密码，默认为guest
    virtual-host: /  #rabbitmq的虚拟主机，默认为/
  # sql打印
  level: debug

  #Thymeleaf配置
  thymeleaf:
    #开启模板缓存（默认值：true）
    cache: false
    #页面检查
    check-template: true
    #检查模板位置是否正确（默认值:true）
    check-template-location: true
    #Content-Type的值（默认值：text/html）
    servlet:
      content-type: text/html
    #开启MVC Thymeleaf视图解析（默认值：true）
    enabled: true
    #模板编码
    encoding: UTF-8
    #要被排除在解析之外的视图名称列表，用逗号分隔
    excluded-view-names:
    #要运用于模板之上的模板模式。另见StandardTemplate-ModeHandlers(默认值：HTML5)
    mode: HTML5
    #在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
    prefix: /templates/
    #在构建URL时添加到视图名称后的后缀（默认值：.html）
    suffix: .html
    #Thymeleaf模板解析器在解析器链中的顺序。默认情况下，它排第一位。顺序从1开始，只有在定义了额外的TemplateResolver Bean时才需要设置这个属性。
    template-resolver-order:
    #可解析的视图名称列表，用逗号分隔
    view-names:

  #Redis配置
  redis:
    # Redis 数据库索引（默认为 0）
    database: 0
    # Redis 服务器地址
    host: localhost
    # Redis 服务器连接端口
    port: 6379
    # Redis 服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制） 默认 8
    lettuce:
      pool:
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 10
        # 连接池中的最大空闲连接 默认 8
        max-idle: 500
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0


#二维码保存路径
qrcode:
  path: /Users/zhouliangjun/Desktop/QrCode/
  #二维码访问路径
  view.path: /Users/zhouliangjun/Desktop/QrCode/

#========================接口服务相关参数配置==============================
# 聚合接口key
juhe:
  api:
    key:
    # 聚合星座key
    constellation:
      key:
      # 聚合星座接口地址
      url:
    # 聚合汇率接口地址
    exchange:
      rate:
        key:
        # 聚合日常汇率接口地址
        url:
    # 聚合汇率货币列表
    currency:
      list:
        url:
#=========================七牛相关配置文件===============================
qi:
  niu:
    resource:
      url:
    access:
      key:
    secret:
      key:
